version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./requirements.txt:/app/requirements.txt